import { expect, type Page } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * Shared route-capture helpers used by the agent UI exploration specs
 * (both the public crawl and the authenticated crawl).
 *
 * For each route we capture the artifacts an agent needs to "understand" a
 * screen without a human in the loop:
 *   - a full-page screenshot (what it looks like)
 *   - an ARIA snapshot (the semantic/accessibility tree — roles, names,
 *     structure — which is how an agent reads a page)
 *   - a summary of headings and interactive controls
 */

export const ARTIFACT_DIR = path.join(__dirname, '..', 'artifacts');

export type Route = {
  /** Path to visit. */
  path: string;
  /** Human/agent-friendly label used for filenames and the index. */
  name: string;
  /** What this screen is for. */
  purpose: string;
};

const slug = (name: string) => name.replace(/[^a-z0-9]+/gi, '-').toLowerCase();

const dedupe = (xs: string[]) =>
  [...new Set(xs.map((x) => x.trim()).filter(Boolean))];

/**
 * Visit a route, write its screenshot + ARIA snapshot to ARTIFACT_DIR, and
 * return the markdown block describing it for the UI map index.
 */
export async function captureRoute(page: Page, route: Route): Promise<string[]> {
  const response = await page.goto(route.path, { waitUntil: 'networkidle' });
  const status = response?.status() ?? 0;
  const finalUrl = new URL(page.url()).pathname;

  const base = slug(route.name);
  const screenshotFile = `${base}.png`;
  const ariaFile = `${base}.aria.yml`;

  await page.screenshot({ path: path.join(ARTIFACT_DIR, screenshotFile), fullPage: true });

  // The ARIA snapshot is the structured view an agent reasons over.
  const aria = await page.locator('body').ariaSnapshot();
  await writeFile(path.join(ARTIFACT_DIR, ariaFile), aria, 'utf-8');

  const title = await page.title();
  const headings = await page.getByRole('heading').allInnerTexts();
  const links = await page.getByRole('link').allInnerTexts();
  const buttons = await page.getByRole('button').allInnerTexts();
  const inputs = await page.locator('input, textarea, select').count();

  // The route should resolve to something renderable.
  expect(status, `${route.path} should not be a server error`).toBeLessThan(500);

  return [
    `## ${route.name} — \`${route.path}\``,
    '',
    `- **Purpose:** ${route.purpose}`,
    `- **HTTP status:** ${status}`,
    `- **Landed on:** \`${finalUrl}\`${finalUrl !== route.path ? ' (redirected)' : ''}`,
    `- **Title:** ${title || '(none)'}`,
    `- **Headings:** ${dedupe(headings).join(' · ') || '(none)'}`,
    `- **Links:** ${dedupe(links).join(' · ') || '(none)'}`,
    `- **Buttons:** ${dedupe(buttons).join(' · ') || '(none)'}`,
    `- **Form fields:** ${inputs}`,
    `- **Screenshot:** [\`${screenshotFile}\`](./${screenshotFile})`,
    `- **ARIA tree:** [\`${ariaFile}\`](./${ariaFile})`,
    '',
  ];
}

/** Write a UI-map index file into ARTIFACT_DIR. */
export async function writeIndex(
  fileName: string,
  heading: string,
  blocks: string[],
): Promise<void> {
  await mkdir(ARTIFACT_DIR, { recursive: true });
  const header = [
    `# ${heading}`,
    '',
    `Generated by Playwright agent exploration on ${new Date().toISOString()}.`,
    '',
    'Each route below has a screenshot (`*.png`) and an ARIA snapshot (`*.aria.yml`) in this directory.',
    '',
  ];
  await writeFile(path.join(ARTIFACT_DIR, fileName), [...header, ...blocks].join('\n'), 'utf-8');
}
