import { test, expect } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * Agent UI exploration.
 *
 * For each public route this captures the artifacts an agent needs to
 * "understand" a screen without a human in the loop:
 *   - a full-page screenshot (what it looks like)
 *   - an ARIA snapshot (the semantic/accessibility tree — roles, names,
 *     structure — which is how an agent reads a page)
 *   - a summary of headings and interactive controls
 *
 * Everything is written to e2e/artifacts/ plus a single UI-MAP.md index.
 * Run with: npm run e2e:explore
 */

const ARTIFACT_DIR = path.join(__dirname, 'artifacts');

type Route = {
  /** Path to visit. */
  path: string;
  /** Human/agent-friendly label used for filenames and the index. */
  name: string;
  /** What this screen is for. */
  purpose: string;
};

const ROUTES: Route[] = [
  { path: '/', name: 'landing', purpose: 'Marketing home page with demo shelves' },
  { path: '/login', name: 'login', purpose: 'Returning-user sign in' },
  { path: '/signup', name: 'signup', purpose: 'New account creation' },
  { path: '/dashboard', name: 'dashboard', purpose: 'Authenticated shelf overview (redirects if logged out)' },
];

const slug = (name: string) => name.replace(/[^a-z0-9]+/gi, '-').toLowerCase();

test.describe('Agent UI exploration', () => {
  const index: string[] = [
    '# UI Map (agent perspective)',
    '',
    `Generated by \`e2e/explore.spec.ts\` on ${new Date().toISOString()}.`,
    '',
    'Each route below has a screenshot (`*.png`) and an ARIA snapshot (`*.aria.yml`) in this directory.',
    '',
  ];

  test.beforeAll(async () => {
    await mkdir(ARTIFACT_DIR, { recursive: true });
  });

  for (const route of ROUTES) {
    test(`capture ${route.name} (${route.path})`, async ({ page }) => {
      const response = await page.goto(route.path, { waitUntil: 'networkidle' });
      const status = response?.status() ?? 0;
      const finalUrl = new URL(page.url()).pathname;

      const base = slug(route.name);
      const screenshotFile = `${base}.png`;
      const ariaFile = `${base}.aria.yml`;

      await page.screenshot({
        path: path.join(ARTIFACT_DIR, screenshotFile),
        fullPage: true,
      });

      // The ARIA snapshot is the structured view an agent reasons over.
      const aria = await page.locator('body').ariaSnapshot();
      await writeFile(path.join(ARTIFACT_DIR, ariaFile), aria, 'utf-8');

      // Summarize the interactive surface.
      const title = await page.title();
      const headings = await page.getByRole('heading').allInnerTexts();
      const links = await page.getByRole('link').allInnerTexts();
      const buttons = await page.getByRole('button').allInnerTexts();
      const inputs = await page.locator('input, textarea, select').count();

      const clean = (xs: string[]) =>
        [...new Set(xs.map((x) => x.trim()).filter(Boolean))];

      index.push(
        `## ${route.name} — \`${route.path}\``,
        '',
        `- **Purpose:** ${route.purpose}`,
        `- **HTTP status:** ${status}`,
        `- **Landed on:** \`${finalUrl}\`${finalUrl !== route.path ? ' (redirected)' : ''}`,
        `- **Title:** ${title || '(none)'}`,
        `- **Headings:** ${clean(headings).join(' · ') || '(none)'}`,
        `- **Links:** ${clean(links).join(' · ') || '(none)'}`,
        `- **Buttons:** ${clean(buttons).join(' · ') || '(none)'}`,
        `- **Form fields:** ${inputs}`,
        `- **Screenshot:** [\`${screenshotFile}\`](./${screenshotFile})`,
        `- **ARIA tree:** [\`${ariaFile}\`](./${ariaFile})`,
        '',
      );

      // Sanity: the route should resolve to *something* renderable.
      expect(status, `${route.path} should not be a server error`).toBeLessThan(500);
    });
  }

  test.afterAll(async () => {
    await writeFile(path.join(ARTIFACT_DIR, 'UI-MAP.md'), index.join('\n'), 'utf-8');
  });
});
